-- 课程主表
CREATE TABLE courses (
    id              INT             NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title           VARCHAR(200)    NOT NULL                    COMMENT '课程标题',
    type            VARCHAR(16)     NOT NULL                    COMMENT '课程类型：INTERNAL/OPEN_OFFLINE/OPEN_ONLINE',
    publisher_id    INT             NOT NULL                    COMMENT '发布者 ID（用户 ID）',
    publisher_type  VARCHAR(20)     NOT NULL                    COMMENT '发布者类型：TRAINER/INSTITUTION',
    category_id     INT             DEFAULT 0                   COMMENT '一级分类 ID（关联 sys_categories）',
    sub_category_id INT             DEFAULT 0                   COMMENT '二级分类 ID',
    cover_url       VARCHAR(500)    DEFAULT ''                  COMMENT '课程封面 URL',
    intro           LONGTEXT                                    COMMENT '课程介绍（富文本 HTML）',
    syllabus        LONGTEXT                                    COMMENT '课程大纲（富文本 HTML）',
    audience        TEXT                                        COMMENT '适用人群',
    highlights      TEXT                                        COMMENT '课程亮点/收益',
    duration_days   INT             DEFAULT 0                   COMMENT '课程天数',
    hours_per_day   DECIMAL(4,1)    DEFAULT 0.0                 COMMENT '每天课时（小时/天）',
    price           DECIMAL(10,2)   DEFAULT 0.00                COMMENT '课程价格',
    original_price  DECIMAL(10,2)   DEFAULT 0.00                COMMENT '原价（划线价）',
    keywords        VARCHAR(500)    DEFAULT ''                  COMMENT '关键词，逗号分隔',
    trainer_id      INT             DEFAULT 0                   COMMENT '关联讲师 ID（专家发布时自动绑定）',
    is_featured     TINYINT         NOT NULL DEFAULT 0          COMMENT '是否主打课程：0=否 1=是',
    is_free         TINYINT         NOT NULL DEFAULT 0          COMMENT '是否免费：0=否 1=是',
    status          TINYINT         NOT NULL DEFAULT 0          COMMENT '状态：0=草稿 1=待审核 2=已上架 3=驳回 4=已下架',
    reject_reason   VARCHAR(500)    DEFAULT ''                  COMMENT '驳回原因',
    sort_order      INT             NOT NULL DEFAULT 0          COMMENT '排序权重（越大越靠前）',
    view_count      INT             NOT NULL DEFAULT 0          COMMENT '浏览量',
    enrollment_count INT            NOT NULL DEFAULT 0          COMMENT '报名人数',
    score           DECIMAL(3,2)    NOT NULL DEFAULT 0.00       COMMENT '综合评分（0.00-5.00）',
    published_at    DATETIME                                    COMMENT '上线时间',
    created_at      DATETIME        NOT NULL                    COMMENT '创建时间',
    updated_at      DATETIME        NOT NULL                    COMMENT '更新时间',
    INDEX idx_type_status (type, status),
    INDEX idx_publisher (publisher_id, publisher_type),
    INDEX idx_category (category_id, sub_category_id),
    INDEX idx_trainer_id (trainer_id),
    INDEX idx_is_featured (is_featured, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程主表';

-- 公开课开课计划表（线上/线下公开课共用）
CREATE TABLE course_plans (
    id              INT             NOT NULL AUTO_INCREMENT PRIMARY KEY,
    course_id       INT             NOT NULL                    COMMENT '关联 courses.id',
    start_time      DATETIME        NOT NULL                    COMMENT '开课开始时间',
    end_time        DATETIME        NOT NULL                    COMMENT '开课结束时间',
    province_id     INT             NOT NULL DEFAULT 0          COMMENT '省份 ID（线下公开课必填）',
    city_id         INT             NOT NULL DEFAULT 0          COMMENT '城市 ID（线下公开课必填）',
    district_id     INT             NOT NULL DEFAULT 0          COMMENT '区/县 ID（选填）',
    address         VARCHAR(300)    NOT NULL DEFAULT ''         COMMENT '具体地址（线下公开课必填）',
    online_url      VARCHAR(500)    NOT NULL DEFAULT ''         COMMENT '开课网址（线上公开课必填）',
    sort_order      INT             NOT NULL DEFAULT 0          COMMENT '排序',
    created_at      DATETIME        NOT NULL                    COMMENT '创建时间',
    updated_at      DATETIME        NOT NULL                    COMMENT '更新时间',
    INDEX idx_course_id (course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公开课开课计划表';
