spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taokewang?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # 密码（没有就留空）
      password: root
      database: 0
      timeout: 10s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5s